### PR TITLE
Add checksums for 5MW meshes

### PR DESCRIPTION
**Pull request by jhux2**
This change is [Reviewable](https://reviewable.io/reviews/exawind/solver-performance/13)

### CODE REVIEW

**Comment by sayerhs** [comment]
Can you provide some context for the origin of these meshes? Specifically what are no rotation and stat meshes? Where are the input files corresponding to these meshes? I assume these are the sliding meshes that are no longer being used for ECP?

**Comment by jhux2** [comment]
> Can you provide some context for the origin of these meshes? Specifically what are no rotation and stat meshes? Where are the input files corresponding to these meshes? I assume these are the sliding meshes that are no longer being used for ECP?

@sayerhs These are the meshes on Cori in /global/project/projectdirs/ECPSolverPerformance/meshes/nrel-5mw.  Input decks are part of this repo.

**Comment by jhux2** [comment]
I don't know what the no-rotation and stat meshes are in g0, maybe @lawsonro3 can say?

**Comment by jhux2** [comment]
@sayerhs I removed the checksums for the stat, rot and no_rotation g0 meshes.

**Review by sayerhs — APPROVED** [review]

**Pull request merged**
