### PR TITLE
ABL: better rebalancing settings

### PR DESCRIPTION
**Pull request by jhux2**
This change is [Reviewable](https://reviewable.io/reviews/exawind/solver-performance/23)

### CODE REVIEW

**Comment by jhux2** [comment]
```
Min No-output time 97.5229 sec
Avg No-output time 98.0564 sec
Max No-output time 99.5298 sec

STKPERF: Total Time: 97.8438
```

```
jsrun --smpiargs="-gpu" -brs -p $size -r 6 -c 2 -g 1 -brs
```

**Comment by lucbv** [comment]
That's fine with me, I was a bit worried that 100k might not be enough work, it would be interesting to see if the improvement is solely driven by reduction in communications?
Also I see you are using different launch options, I usually keep things simple with 
```
jsrun --smpiargs="-gpu" -brs -n $ranks -a 1 -c 1 -g 1
```
I see how `-c 2` is allowing more work on the CPU, do you know what benefits from it in our software stack?
I am guessing that `-p` is the same as `-n`?
You have a duplicate `-brs` in there...

**Review by lucbv — COMMENTED** [review]
lgtm

**Comment by lucbv** [comment]
@jhux2 you will need to add another reviewer to merge this.

**Comment by jhux2** [comment]
@jjellio recommended using c>1.  Good catch on the repeated `brs`, although I don't think it harms anything.  `-p` and `-n` aren't exactly the same.  `-n` assumes that things divide evenly, which they don't in my case.

**Comment by jhux2** [comment]
@sayerhs Can you add @lucbv as an authorized approver?

**Comment by sayerhs** [comment]
@lucbv Can you try again please?

**Review by lucbv — APPROVED** [review]

**Comment by lucbv** [comment]
@jhux2 @sayerhs 
Yep that works now.

**Comment by lucbv** [comment]
@jhux2 that `-p` is actually not documented [here](https://docs.olcf.ornl.gov/systems/summit_user_guide.html#job-launcher-jsrun) and I am not sure what the `things divide evenly` means?
Based on these I would actually be curious to look at the script you used to launch your jobs.

**Comment by sayerhs** [comment]
@jhux2 From what I understand of `jsrun` there is `-n` and `-r` there is no `-p`, I suspect you were talking about `-r` (resource sets per node)?

**Comment by lucbv** [comment]
@sayerhs actually I just ran `jsrun --help` (arguably should have done that earlier...) and there is indeed a `-p` option that reads:
```
  -p, --np=<#>               Number of processes.
```
It does not say how these are actually interacting with the resource sets.

**Comment by jhux2** [comment]
@sayerhs My understanding is that `-n` is the number of resource sets and must be divisible by the value specified by `-r`.  Option `-p` is the total number of MPI processes.  See https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/jsm/jsrun.html

**Comment by jhux2** [comment]
> I see how `-c 2` is allowing more work on the CPU, do you know what benefits from it in our software stack?

From my limited testing, using c>1 give a few percent improvement on the `abl05m` runs.

**Comment by jjellio** [comment]
`-p` is from the spectrum manual.  Not sure why summit doesn't give a clear example of how to run w/out a modulo `-r` job.

`-c` depends on `-brs`, which when both are used gives you a 'core' (rather than a hardware thread).   You need atleast 1 HT per thread your app spawns, and spectrum/cuda are going to give you atleast 5.  I recommend `-c >= 2`.  With the apps I've used we set `-c` to be the somewhere between the 2 and 1-max. The max should be 7 ( I think!).  So I'd try `-c=2...-c=7 + -brs`, and pick the one that works best.  `c=1 w/out -brs` consistently performed substantially (>50%) slower. `c=1 w/brs` always was the worst of all `-c's` I swept.

**Pull request merged**
